TestShop/ViewModels/CarsListViewModel.cs
using System.Collections.Generic;
using Shop.Data.Models;

namespace Shop.ViewModels {
    public class CarsListViewModel {
        public IEnumerable<Car> allCars { get; set; }
        public string currentCategory { get; set; }
    }
}

TestShop/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using Shop.Data.Models;

namespace Shop.ViewModels {
    public class HomeViewModel {
        public IEnumerable<Car> favCars { get; set; }
    }
}

TestShop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;

namespace Shop.ViewModels {
    public class ShopCartViewModel {
        public ShopCart shopCart { get; set; }
    }
}

TestShop/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;

namespace Shop.Controllers {
    public class CarsController : Controller {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCatergories) {
            _allCars = iAllCars;
            _allCategories = iCarsCatergories;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category) {
            IEnumerable<Car> cars = null;
            var currCategory = "";
            if (string.IsNullOrEmpty(category)) {
                cars = _allCars.Cars.OrderBy(i => i.id);
            }
            else {
                if (string.Equals("Electro", category, StringComparison.OrdinalIgnoreCase)) {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName == "Электромобили").OrderBy(i => i.id);
                    currCategory = "Электромобили";
                }
                
                if (string.Equals("Fuel", category, StringComparison.OrdinalIgnoreCase)) {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName == "Классические автомобили")
                        .OrderBy(i => i.id);
                    currCategory = "Классические автомобили";
                }
            }

            var carObj = new CarsListViewModel {
                allCars = cars,
                currentCategory = currCategory
            };
            ViewBag.Title = "Страница с автомобилями";
            return View(carObj);
        }
    }
}

TestShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.ViewModels;

namespace Shop.Controllers {
    public class HomeController : Controller {
        private readonly IAllCars _carRep;

        public HomeController(IAllCars carRep) {
            _carRep = carRep;
        }

        public ViewResult Index() {
            var homeCars = new HomeViewModel {
                favCars = _carRep.getFavCars
            };
            return View(homeCars);
        }
    }
}

TestShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;

namespace Shop.Controllers {
    public class OrderController : Controller {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart) {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout() {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order) {
            shopCart.listShopItems = shopCart.GetShopItems();
            if (shopCart.listShopItems.Count == 0)
                ModelState.AddModelError("no_items_in_cart", "У вас должны быть товары!");
            if (ModelState.IsValid) {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete() {
            ViewBag.Message = "Заказ успешно обработан!";
            return View();
        }
    }
}

TestShop/Controllers/ShopCartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;

namespace Shop.Controllers {
    public class ShopCartController : Controller {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRep, ShopCart shopCart) {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        public ViewResult Index() {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;
            var obj = new ShopCartViewModel {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id) {
            var item = _carRep.Cars.FirstOrDefault(c => c.id == id);
            if (item != null)
                _shopCart.AddToCart(item);
            return RedirectToAction("Index");
        }
    }
}

TestShop/Views/Cars/List.cshtml
<h1>Все автомобили</h1>
<h3>@Model.currentCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.allCars) {
            @Html.Partial("AllCars", car) //передаём объект car в AllCars.cshtml
        }
    }
</div>

TestShop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Избранные автомобили</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (var car in Model.favCars) {
            @Html.Partial("AllCars", car) //передаём объект car в AllCars.cshtml
        }
    }
</div>

TestShop/Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="first_name"></label>
            <div class="col-md-5">
                <input asp-for="first_name" class="form-control"/>
                <span asp-validation-for="first_name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="last_name"></label>
            <div class="col-md-5">
                <input asp-for="last_name" class="form-control"/>
                <span asp-validation-for="last_name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="address"></label>
            <div class="col-md-5">
                <input asp-for="address" class="form-control"/>
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control"/>
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control"/>
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Завершить заказ"/>
    </form>
</div>

TestShop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

TestShop/Views/Shared/AllCars.cshtml
@using System.Globalization
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name"/>
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Цена: @Model.price.ToString("c", CultureInfo.CreateSpecificCulture("en-US"))</p>
    <p>
        <a class="btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Добавить в корзину</a>
    </p>
</div>

TestShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/css/style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Автомагазин</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List">Машины</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/Electro">Электромобили</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/Fuel">Классические автомобили</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart/">Корзина</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Поиск">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </nav>
</header>
<div class="container mt-5">
    @RenderBody()
</div>
<footer class="container">
    <p class="float-right">
        <a href="#">Back to top</a>
    </p>
    <p>© 2021 Aleksei Lomakin <a href="#">Соглашение</a></p>
</footer>
<script src="~/js/bootstrap.min.js"></script>
</body>
</html>

TestShop/Views/ShopCart/Index.cshtml
@using System.Globalization
@model ShopCartViewModel
<div class="container">
    @foreach (var el in Model.shopCart.listShopItems) {
        <div class="alert alert-warning mt-3">
            <b>Автомобиль:</b> @el.car.name <br/>
            <b>Цена:</b> @el.car.price.ToString("c", CultureInfo.CreateSpecificCulture("en-US")) <br/>
        </div>
    }
    <hr/>
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>
</div>